global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'medicure-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']  # Change to container/cluster IP as needed
