apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-prod-deployment
  labels:
    app: medicure-app
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure-app
  template:
    metadata:
      labels:
        app: medicure-app
    spec:
      containers:
        - name: medicure-container
          image: deorepooja/medicure-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-prod-service
spec:
  type: LoadBalancer
  selector:
    app: medicure-app
  ports:
    - port: 80
      targetPort: 8080
